### ISSUE TITLE
failed to annotate

### ISSUE THREAD

**Issue by michaelcapizzi** [myedibleenso/py-processors#2]
Certain lines of the COCA dataset fail to annotate (`proc.annotate(text)`) with this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Utils/PreProcessing.py", line 23, in annotate
    return proc.annotate(text)
  File "/media/mcapizzi/data/Github/py-processors/processors/processors.py", line 113, in annotate
    raise Exception("Connection refused!  Is the server running?")
Exception: Connection refused!  Is the server running?
```

Here is one such line (note: each line is a full transcript of a radio episode):

```
 I 'm Gwen Ifill .
Jim Lehrer has the holiday off .
On the NewsHour this Fourth of July , the GI Bill and American prosperity with NewsHour regulars Haynes Johnson , Michael Beschloss and Doris Kearns Goodwin , plus historian Stephen Ambrose ; Ray Suarez explores the lasting appeal of the all- American artist , Norman Rockwell ; Margaret Warner talks fly-fishing with author Richard Louv ; essayist Roger Rosenblatt considers the pursuit of happiness ; and we remember dancer Harold Nicholas , who died yesterday .
It all follows our summary of the news this holiday Tuesday .
On this Independence Day , there were celebrations from coast to coast ; among them , a parade of tall ships , " Opsail 2000 " in New York Harbor .
The vessels sailed from around the world .
They were joined by U.S.
Navy warships , as well as Coast Guard cutters .
President Clinton viewed the scene from the aircraft carrier " John F.
Kennedy .
George Washington ordered it to be read allowed to the troops .
It was at the tip of Manhattan Island , just to our north , where the troops first heard they were actually citizens of a new nation .
-- where they first heard the words , " we hold these truths to be self-evident .
" And where they first pledged their lives , their fortunes , their sacred honor .
First Lady Hillary Clinton and daughter Chelsea also joined the President for the day 's ceremonies .
Saudi Arabia , the world 's largest oil exporter , announced late Monday it will soon raise oil production .
The country 's petroleum minister said it was ready to increase output by 500,000 barrels a day .
But other members of OPEC , the petroleum-producing cartel , said they have not been consulted on such a move .
The cost of crude has been above $30 a barrel , keeping gasoline prices high .
That will be the first time sisters have ever faced off in the final rounds of a grand slam tournament .
Tap dancer Harold Nicholas died Monday of heart failure at age 79 .
He and his older brother , Fayard , started out in Vaudeville as children .
They went on to dance on Broadway , on television and in more than 50 movies .
We 'll have a sample of their work at the end of the program tonight .
Between now and then , 50 years of the GI Bill , artist Norman Rockwell , a conversation about fly-fishing and a Roger Rosenblatt essay .
On this Independence Day , Spencer Michels begins our look at the GI Bill and the impact it 's had on the country .
At Harvard and many other colleges around the country it 's reunion time again .
The returning alumni include the class of 1950 .
The two former classmates at Georgetown University celebrated their golden anniversary last month .
During the war Padelford served in infantry camp in Camp Landings , Florida .
Every day the people who were training us would say , " You 're going to be in on the invasion of Japan , " because we were in something called an " infantry replacement training depot .
The invasion never happened , of course , because Japan surrendered after the atomic bombs were dropped .
Mosher served as a paratrooper in France .
I ended up in the 101st Airborne Division and we were located - my company was located in a small French town called Mormala Petite .
This was , I would think , about eighty to a hundred clicks away from Paris .
Before World War II , U.S.
veterans who were not disabled received few , if any , benefits upon their return home .
I came to Washington to get my bonus , and I 'm going to wait till I get it if I have to wait till 1945.
The bonus marchers were driven out of town by the U.S.
Army and never received their early payments that year .
But a decade later , during World War II , the American Legion joined forces with newspaper baron William Randolph Hearst and crafted the Servicemen 's Readjustment Act , also known as the GI Bill of Rights .
President Roosevelt - planning for the eventual return of 12 million soldiers to the economy and mindful of the angry bonus marchers from 30s - was favorably inclined .
We are laying plans for the return to civilian life of our gallant men and women in the armed services .
They must not be demobilized into an environment of inflation and unemployment to a place on the bread line or on a corner selling apples .
Among the key benefits was education .
Any veteran who served 90 days , regardless of color or financial situation , qualified for up to $500 per term for vocational school or for college .
Ed Pidelford said that 's what made University affordable for him and most of his peers .
I probably could not have attended college unless I really had saved a great deal of money , because my parents were just ordinary .
We were n't poor , but they did n't have any - enough money that they could have afforded to send me to college .
The wonderful thing about the GI Bill was , of course , the fact I did not have to work .
My wife did work , but I did not have to .
" The veterans doubled college registration in the 1940s , forcing schools to build temporary housing facilities .
In addition to education , the law provided low-interest home mortgages backed by the federal government .
That sparked a demand for new homes in the post war years - a key ingredient to the exploding growth of suburbia.
After I got hold of the GI Bill and we bought a house in Rockville , Maryland , at the fantastic rate of 4 1/4 percent interest , which I thought was very , very high in those days .
In fact , when we finally sold that house , I lost my GI Bill .
I went to 5 1/2 percent , and I was very , very upset about that .
The GI Bill also provided business loans to veterans , established veterans ' hospitals , and provided unemployment benefits that included a $20-a-week allowance for up to a year , the so-called 52/20 Club .
It doubled the ratio of homeowners from one in three before the war to two in three afterwards .
And according to a 1986 government study , each dollar invested in the bill yielded 5 to 12 dollars in tax revenues .
Over the years , the GI Bill has been called many things by historians and veterans alike - a Marshall Plan for America , a Magic Carpet to the Middle Class .
Well , I think the term the " magic carpet " probably is correct .
I mean , as I said , it enabled me to go to college , which I doubt whether -- without it I could n't have done that , and it enabled me to make a career in the State Department and the Foreign Service , not to mention the Air Force Reserve .
It eventually got me up to Air Force Colonel .
And so it was - it was essential - the GI Bill .
Without it , none of these things could have occurred .
And , I mean , I had never expected to get anything out of it .
So whatever I got , be it GI Bill , be it the home loan , whatever , it was all a fantastic bonus that I had not counted on , that I had not expected .
And it made my life very , very much easier .
The original GI Bill expired in 1956 .
Scaled back versions were offered to veterans of the Korean and Vietnam Wars , and today , a law known as the Montgomery GI Bill provides education and job training benefits as an incentive for military recruits .
Jim Lehrer recorded this discussion about the GI Bill just before the holiday .
Now , some further perspective on the GI Bill from NewsHour regulars Presidential Historians Doris Kearns Goodwin and Michael Beschloss , journalist/author Haynes Johnson ; joining them tonight Historian Stephen Ambrose , who 's written extensively on World War II .
His last book was " Citizen Soldiers , the U.S.
Listen , that GI Bill was the best piece of legislation ever passed by the U.S.
Congress , and it made modern America .
The educational establishment boomed and then boomed and them boomed .
The suburbs , starting with Levittown and others , were paid by GIs borrowing on their GI Bill at a very low interest rate .
Thousands and thousands of small businesses were started in this country and are still there thanks to the loans from the GI Bill .
It transformed our country .
Transformed our country , Doris ? Oh , no question .
I agree with everything Steve said , including the passion with which he said it .
I think few laws have had so much effect on so many people .
I mean , think about it .
In 1940 , the average GI was 26 years old and had an average of one year of high school as his only education , and now , suddenly , the college doors were open .
I mean , it 's so amazing to realize that the university presidents thought it was a terrible idea at first .
The president of Harvard said it would create unqualified people , the most unqualified of this generation coming into college .
The president of the University of Chicago feared we 'd be creating educational hobos , but as the piece earlier showed , these were mature , responsible people , the best of their generation in college .
It shows what happens when you give people who do n't have a chance an extraordinary opportunity .
Extraordinary , amazing , Haynes , those words do jump to mind , do n't you think ? It made a difference .
Steve Ambrose got his graduate degree in Wisconsin .
I was on the GI Bill after Korea , and I got a scaled down version , but that 's how I got my graduate degree .
I bought my first house on the GI Bill .
Yeah .
There you are .
I mean , the idea of this - it is so incredible to look back on that - the idea that in 1940 - in the class of ' 40 , as Doris would say , five years after the war - World War II - ended , twice as many Americans graduated from college .
That 's just the college part .
I mean , as Steve was saying about the suburbs , there were 13 million homes built in the 50 's , 11 million outside of there with GI loans .
I mean , it just - it did transform the country .
He signed this bill two weeks after D-Day .
He had spent much less thought on this than he did on most of the New Deal , but if you look at the effect of this , this had much greater impact on bringing Americans into the middle class than everything Roosevelt had tried to do over eight years in the 1930 's , and there were all sorts of other unexpected consequences .
One was the fact that Americans did move to the suburbs , a good thing in many ways because a lot of people owned houses that they never could have before the war .
They used to be renters ; they were owners after World War II .
Do you read the record the same way , or that what they were really aiming to do was to reward the veterans , not to change American society , but it just happened ? Oh , yes , that 's absolutely right , and let 's remember , this does go back to the Revolutionary War .
Revolutionary War soldiers got land bonuses after the war was over and America has always tried to do something for its veterans after the Civil War - did n't do very well after World War I , which is why the Bonus Mark had to take place .
But the GI Bill was designed to help veterans , not to transform America .
No one had that idea in mind .
God , they worked so hard , and they - all of them - came back to America feeling I just wasted the best years of my life .
I know how to man a machine gun ; I know how to fire a mortar ; but I ca n't make a living out of this .
And now they had college opened up to them , and these guys went on a make of 21 hours a semester , 24 hours a semester , and they worked .
They just wanted to get that education .
I lived in a small college town in Wisconsin , and the houses all around us were divided up into little rooms where the GIs could stay .
And the only recreation they ever took was we 'd do an hour of basketball and then it was right back to the books for them , and they 're the students that every teacher in this country would just kill to have .
But , Steve , what drove them to go to school ? They did n't think about going to college when they went into the army .
They matured .
They came to see the benefits that are available if you go out and get yourself educated and then if you work at it , and they brought to going to college a sense of responsibility and a sense of " I want to get ahead .
And if you do that job well , you 're going to get promoted again , and pretty soon you 're going to be in officer 's candidate school .
And then you 're going to get a battlefield commission and then you 're going to go from lieutenant to captain and captain to major and so on .
They saw it with their own eyes .
They experienced with their own bodies the joys of moving ahead .
And , Doris , to use the word transforming society , I mean , the legacy of what happened to those World War II vets continues to this day , does it not , in our society ? Oh , without question , it 's the generation that really built the whole decades that followed after that .
You know , just following on what Steve said , most of the people who went into the GI - into the soldier 's war - had not left their counties ; they had n't traveled much in the United States .
So possibilities open to them , and I think that 's partly what led to that changing attitude toward their educational possibilities I 'm going to take advantage of as well .
The other thing that 's so interesting to remember is that during this debate it was opened up as a possibility that the war workers at home would be eligible as well for the GI Bill of Rights , and think of what that would have meant .
Women - 60 percent of the jobs in the shipyards and the airplane factories held by women - instead of those women going home and being thrown out of work and then becoming a generation that really did n't move forward until the next generation , think of the social revolution that might have prevailed .
You know , Haynes , it 's staggering to think also what if there had been no GI Bill ? Horatio Alger - all of that - but this made it possible to go to college , and that was n't the case of most Americans .
They actually had the opportunity .
And the irony of this - we 're talking about - this was the biggest government grant - in effect - it was the government - federal government -- because ( a ) people hate the government .
This was once there was no debate about it .
There 's no controversy about it .
There 's no ideological argument about it .
Why is that , Michael ? Because it succeeded so well - that 's the first thing .
At the time that the bill was debated in Congress it passed only by a very slim margin , and , in fact , a lot of particularly Republicans said let 's not pass this thing because a big part of the GI Bill was to give returning vets $20 a week for 52 weeks .
They felt that would encourage sloth ; that people would not try to get jobs .
They thought that this would extend the welfare state , rather than do the opposite .
But the other thing I think really endures as a part of America 's philosophy is this linked the idea of service to education .
You serve the country ; the government pays you back by allowing you educational opportunities you otherwise would n't have had , and that in turn helps to approve this society .
That 's something that goes al the way back to the time of he Revolution , and I think it 's one reason why we think of it so fondly .
Yeah .
Absolutely .
Listen , Haynes and I - ( laughter ) - just think what it did in Madison or in Cambridge or in East Lansing or in Berkeley .
Later on , that figure was moved up , and they could and study and work and improve themselves , and the institutions that served them , that grew out of this - like the state teacher 's colleges in Wisconsin -- or like Harvard and all the others in between - they all benefited from it .
And , Doris , there 's also the housing thing .
Oh , absolutely .
I mean , most of those people were living in cities , often on the wrong side of the tracks , and then they got a chance to own their own home .
Education provided that opportunity for millions of people , made the promise of America real from the Homestead Act of 1862 , which gave them a little patch of land , now to that home that they could own and the education to allow them to be what they could be .
It 's a great moment , and I 'm so glad we 're able to remember it like this .
Michael .
I hate to be a downer .
One thing that it did n't work so well at was helping black Americans .
Many black Americans who got GI benefits could not get into some of these towns - Levittown on Long Island was segregated .
You could n't buy a house if you were black .
Would give you the money and would give you the money to go to a school , but oftentimes colleges were segregated too .
It took civil rights legislation on the Supreme Court in the 50s and 60s to really make the GI Bill do what it ultimately was able to do .
Yeah .
Well , I think the nature of the country and the way we live today , the highways , the cars , the suburban element of it is - that 's what America is now .
We are no longer in the central cities of our country , and the idea - what Michael is talking about - civil rights - that came later .
We focused on civil rights and women 's rights - tremendous changes there - but this one came first - and then the integration of the armed forces and then the civil rights , and they all kind of together , I think , really made the difference .
And thank you all four very much .
Still to come on the NewsHour tonight , a Norman Rockwell retrospective , author Richard Louv , essayist Roger Rosenblatt and remembering Harold Nicholas .
Next , a new look at an all- American artist .
Ray Suarez has that story .
What do you see when you look at a Norman Rockwell painting ? We think about the subject and not the quality of the art work .
And the art work is tremendous , so they are very nice for art 's sake , and I can put up with the corniness , too .
" I think his artwork is so happy .
His paintings are ...
They just bring joy , every single one , almost , just makes me feel like a kid again .
I do n't consider him saccharine at all .
I do n't know many people that do n't really enjoy looking at his paintings .
They just ...
Brings a smile to your face .
Norman Rockwell himself said , " I 've always wanted everybody to like my work .
I could never be satisfied with just the approval of the critics .
So I 've painted pictures that did n't disturb anybody , that I knew everyone would understand and like .
" And that makes perfect sense when you consider where the artist reached his public -- in mass-produced magazine covers , and advertisements .
Rockwell 's images grab our attention in just a few seconds .
The plot is easy to understand , instantly readable .
The drama is filled with recognizable characters .
All of them , along with the original oils that became the covers and ads , are part of the first comprehensive exhibition of the artist 's work , since his death in 1978 , now on display at Washington 's Corcoran Gallery of Art .
There are images commissioned for Boy Scout calendars and advertisements , each capturing a slice of American life .
Pictures for the American People : Rockwell had success very early in his career and I think he always knew that he was very , very , good at what he did .
Maureen Hart-Hennessey is the curator of " Norman Rockwell : Pictures for the American people .
I think it probably bothered him very much that he was dismissed as being merely , or only an illustrator .
He is quoted as having said that a lot of people came up to him and said , " I do n't know much about art , but I like your art .
During his life , Rockwell did n't get the kind of respect he sought .
But today , many critics and art historians are ready to give him his due , as a skillful painter , and a chronicler of American life .
Rockwell was born in 1894 in New York City .
As a teenager , he left high school for art school , and started getting paid for his work before he was 20 .
His work spanned most of the 20th century .
His paintings asked young men to join the fight in the first world war , urged factory workers to keep the boys supplied in the second , and showed us astronauts landing on the moon in 1969 .
Rockwell was inspired to paint a series of patriotic images after hearing Franklin Roosevelt 's 1941 state of the union address in which the President outlined what he called the four basic freedoms .
Commissioned by the Office of War Information , a propaganda arm of the U.S.
Government , the paintings are among the most reproduced in history .
More than one million people saw " the four freedoms " during a nationwide tour which raised $132 million in war bonds .
The paintings show his real affection for common folk , his deep patriotism , and in " Freedom from Want , " perhaps his best known picture , you can see Rockwell 's mastery of light and color ; the curtains , the apron , the tablecloth and the platter all in subtly different shades of white .
The artistry itself presents a predicament .
Though America was torn by rapid breakneck economic and technological change , Depression and war , Rockwell used his prodigious talent in the service of business .
The " Prayerful Silence , " worthy of a Flemish master , sold raisins .
His use of models from his New England home towns results in an America that is virtually all white .
Instead , we got prom couples , cute as buttons ; dogs that always seem to stay puppies ; lovable old codgers , and grandmothers who look like , well , grannies -- a world where it rarely rained -- that is , until the later years .
In 1963 , Rockwell left " the Saturday Evening Post " and began work for " Look " magazine where he explored more controversial issues such as housing integration and school desegregation , as in this work , " The Problem we all Live with .S.
Marshals .
But there 's a real violence inherent , I think , in that scene .
You can see where the tomato has been thrown at the ...
At the child , and the words that are scrawled on the wall behind her that it could explode at any moment -- and he really captures that .
Most of Rockwell 's characters were real people .
His neighbors were his models , as was his son , now a sculptor , Peter Rockwell.
There 's one particular picture which I 've felt strongly about since then because he has me in it looking like the wimp I was when I was 13 .
And I keep looking at it and think , did I look that awful and did I have , did I actually wear those silly glasses then ? There was one time when I 'd posed for " The Boy in the Dining Car , " and it was the hottest day of august of 1946 , I think .
And so he finally said , look , he said , " if you 'll just pose and do it , as soon as it 's over I 'll take you to FAO Schwartz and buy you anything you want .
Did it work ? Yes , it did .
Curator Hart-Hennessey gives us a guided tour of one Rockwell masterpiece .
" The Girl at the Mirror " was done for the cover of the " post " in 1954 , and it 's probably one of his best-known , and I would even venture to say best-loved images .
Her doll 's been thrown aside , but she 's still within arm 's reach , almost saying , " well , I 'm not quite through playing with her yet .
" And she has her makeup and the comb and brush very close at hand , and she has this wonderful look on her face that 's kind of a mixture of sadness and wonder .
The tremendous attention to detail in these canvases was all the more remarkable when you consider that virtually no one saw these paintings as paintings , only as reproductions in the flattened out , less subtly colored world of the mass-produced magazine cover or display ad .
That did n't matter to Rockwell .
He took great pains for authenticity , and packed his paintings with detail .
It 's clear that Rockwell also saw the paintings as a final in and of themselves .
There are little jokes in some of the paintings .
There is a painting of the baby sitter that was done for the cover of the " Post " where she has a diaper over the arm of the chair and there 's a diaper pin in it ...
the surface of the painting as well .
Still , for years , Rockwell 's realistic images stood in stark contrast to the 20th century 's abstract and expressionist art , the tumult and self-examination of the artists around him .
His art was displayed on newsstands , not in museums  I 'm going to kind of put you on the spot .
Well , of all time ? There 's no doubt .
Rembrandt -- yeah .
I mean , he was the greatest .
I mean , he ...
To me a Rembrandt painting , any of his paintings , they 're like a beautiful symphony .
I mean , they have these great , deep notes .
He understood humanity .
And he 's just the greatest .
For paintings he was ...
He was a real intellectual in the sense that he was a very rationale composer of paintings .
He knew a great deal about European painting .
Here , a very proper museum-goer considers a very good Jackson Pollock imitation , of course painted by Norman Rockwell .
An art student examines an old master , much to the delight of the lady herself , and the gentlemen in nearby paintings .
His strong and confident " Rosie the Riveter , " first was painted by Michelangelo as Isaiah on the ceiling of the Sistine chapel .
In 1960 , " The Saturday Evening Post " published a biography of the by-now very famous artist ...
So there 's this whole series of self-portraits going on .
Each one is a different character .
He 's slightly caricaturing the figure sitting there on the chair .
The face in the mirror is very intense and very serious and interestingly enough you do n't see the eyes because the glasses are reflecting .
Then he 's got pinned up on it , he 's got a Durer 's self-portrait , a Rembrandt 's self-portrait , a Picasso self-portrait behind a woman and a Van Gogh self- portrait .
Is he saying that these self- portraits that we see of theirs are really not the real them ? Or is he just saying this is , you know , this is , these are my great gods .
In other words , he 's thinking about self-portraiture .
Yet , at the same time , he 's giving you so many different images of himself that he 's never saying who he is.
So , he 's asking a lot of questions and he 's not really giving any answers ? Well , yes .
Exactly .
That 's the whole point of the painting in one level is to ask a lot of questions .
" Norman Rockwell : Pictures for the American People " leaves Washington 's Corcoran Gallery on September 24 .
It then travels to San Diego , Phoenix , Stockbridge , Massachusetts , and New York City between now and March , 2002.
Now , another of our conversations about new books , and to Margaret Warner .
The book is " Fly-Fishing for Sharks : An American Journey " by Richard Louv .
It 's his account of his two years traveling around the country , exploring how and why anglers fish , and why they love it so .
An avid fisherman himself , Louv is also a columnist for the " San Diego Union Tribune .
" Welcome , Richard .
Why did you embark on this book ? It 's hard to imagine a journalist traveling around the country talking to , say , ordinary people about why they play tennis .
I had written five books prior to that , and I said , " you know , all I have here are depressing social issues again , and every time I think of writing another book about a depressing social issue , I get a headache .
" And he said , " well , have you ever thought about writing a book about fishing ? " And I said , " why ? " And he said , " Because your affect changes .
Every time you talk about it , it makes you happy .
" And that really , I think , is the key to why one would look at America through this window of fishing .
I also wanted to look at America in a new way .
Well , it 's a very generous country .
I mean , really the truth about America is n't in the headlines .
It 's in the small details .
It 's in the folks you meet , you know , when I walked up the East River into Spanish Harlem , and then the next day over to Harlem and talked to the guys that fish along there .
You know , it 's in the folks who are so passionate about fly- fishing in Montana .
It 's in the women who have learned that fishing is a terrific thing to do , and that they 're often better at it than men are .
It 's in the stories that people tell about their lives , and about America .
And this is n't a cynical country when you see it through the window of fishing .
These people are passionate .
They 're not cynical .
They 're engaged with nature , which is something we 're also losing in the country , I think .
Well , you 're right .
44 million people fish regularly .
It 's a $50 billion industry .
It 's grown a lot over the last 15 years .
The best way to explain , I think , why people fish is a Montana guide I was with going down a river in Montana .
We spent all morning fishing and had n't caught anything .
And there was an old guy in the front of the boat , and I was in the back .
And this old Montana guide , we finally caught one -- the old guy in the front caught one -- got all excited .
He was grinning ; I was grinning .
I turned to the guide and said , " you know , what is it about fishing ? Do you mean that literally or metaphysically ? " And he says , " well , both .
" And I think that is kind of the key to why people fish .
In that moment when you catch a fish nothing else matters .
The past disappears .
The future does n't exist .
You do n't think about it .
You do n't think about work .
It really puts you in connection with something really greater than yourself .
You quoted one ...
I think he was a guide who talked about that you almost enter something he called river time through the intense concentration .
Right , an altered state , really , and anglers all over the country talked about that altered state .
And also , women who fish often talked about their interaction with nature being different than men 's .
I was impressed by that .
I have a phrase in the book called " deep fishing , " and this is when people really ...
everyday life disappears .
I mean , to be a good fly-fisher , you 've almost got to be an entomologist.
Sure .
You have to know what the bugs there mean about which ...
what the fish are eating and ...
Right , right .
But this river time or this deep fishing , this altered state goes really beyond kind of intellectual knowledge about nature .
It goes into another space .
People often talk about the spiritual side of fishing , and I noticed that in your book , in your conversations , a lot of people talked about their connection with God and nature and their place in it .
Yeah , it is .
Some anglers will go out of their way to put that aside and not talk in those terms , but many , many did , from all walks of life .
I mean , every family has somebody who fishes in it who tells stories about fishing .
How did you find that fishers who are , many , so in touch with nature , how do they resolve the conflict between that and the fact that fishing is hunting and often killing , though a lot of people now catch and release the fish ? I think the folks who think about it as the spiritual endeavor probably understand that more deeply .
And PETA , the organization , a leading animal rights organization , has targeted fishing and in fact e starting to go into schools , starting to stand outside the schools that wo n't let them in , and convince kids that this is n't a good thing to do .
I think they raise good ethical issues , but so have anglers , f for a long time , about catch and release .
I mean , there are dams coming down in America because people have kept fishing journals for hundreds of years that go back ...
in their family , they 've watched how rivers and streams have changed , and they present that as evidence .
And dams have been brought down because of that .
Also , there 's this whole issue of direct experience of nature .
Children are , I think , losing that sense of direct experience .
I mean , as by boomers , we 're probably the last Americans to have some kind of direct familial contact with agriculture , with nature .
You know , we all had an uncle or an aunt or a grandfather who lived on a farm .
Maybe we visited them .
In 1993 , the U.S.
Census Bureau quit giving out its report on the farm population in America because there is n't any left , for the most part .
One is we tend to romanticize nature on the one hand , or we forget about it and we do n't care about it .
I think kids today in particular are starved for some direct connection with nature , and fishing has been a traditional way to for them to do it .
And the truth is that it is messy .
It 's morally messy .
And I do n't think that anyone can really learn truly about nature through binoculars or on videotape ; they have to get their hands dirty .
So when you say morally messy , because you do have to confront this issue of whether you 're taking a life ...
Yes , yeah .
And you have to understand too that that life that you may or may not be taking may have taken a life that morning .
I mean , that bass may have eaten a duckling three hours earlier .
Well , first , to describe that loss , in interviewing kids around the country , I think the polarity of that relationship between children and nature has reversed .
When I was a kid , I spent a lot of time in the woods , in the fields , and along the creek , and they were my woods and my fields .
I owned them in my mind , to the extent that I pulled out hundreds of survey stakes that I knew had something to do with the bulldozers .
But I did n't know anything about global warming or any of the great ecological issues , did n't know that my woods were connected to other woods .
Kids today can tell you anything about global warming or the Amazon Rain Forest .
What they ca n't tell you is the last time they went out and experienced the woods in solitude .
So with that reversal comes all kinds of implications .
What happens to a kid 's emotional health , given that disconnection ? So we 'll give them all a fishing rod .
Thanks , Richard Louv , very much .
Thanks .
Now , essayist Roger Rosenblatt offers his perspective on what makes Americans happy .
Leave it to Thomas Jefferson to start the country on its way by wishing it a mission seemingly impossible .
Taking John Locke 's triad of human rights -- life , liberty and property -- Jefferson changed the third item to " the pursuit of happiness " -- something that no other civilization -- monarchial , totalitarian or democratic -- would dare to set forth .
The pursuit of happiness as a right .
In a recent article in the " New York Times Magazine , " author Andrew Delbanco wonders about that , noting wisely that , Jefferson 's language aside , that right has never been self- evident .
By the time America realized itself , happiness could be seen in good works ; socially useful projects .
In our own dot-com and NASDAQ times , happiness may have returned to Locke 's property again .
The pursuit of a second home , a convertible , a dream boat .
On July 4 , one might look into this idea .
Did Jefferson design a country in which along with life and liberty came the right to pursue stock options , a Picasso at an auction , the lottery , one 's own Lear Jet , a rented bungalow in the Hamptons for $350,000 .
How happy can one get ? The question is not rhetorical .
Not only does one fail to buy happiness by the acquisition of goods , one knows that one fails .
I 've got a man In London who buys all my clothes .
The splendid scene of the shirts in the " Great Gatsby .
Daisy sobs out of control .
Why ? Because she 's a little nitwit , to be sure , but also because she holds the American dream and the American heartbreak both in her hands .
So are we , when asserting the right to pursue happiness , actually speaking about the pursuit of unhappiness ? Delbanco strongly suggests this in his essay , and it 's a tantalizing , if unnerving , thought .
Sob if you will , the eternal round of getting and yearning fires the American engine .
The state of not having gives us the frontier again .
Ah , the Mississippi .
Ah , the Rockies .
Oh , pioneers .
Three , two , one ...
When we run out of real estate , we head for the moon , the planets , the stars .
When we run out of those , we can always buy shirts , the getting of which throws us back like lightweight fabrics upon our eternally unsatisfied selves .
And I seem to find the happiness I seek ...
" I seem to find it , but I do n't .
" The things we want that we can have always imply the things we can not have .
Is unhappiness really the goal ? That would be strange , weirdly self-punishing .
Of course happiness does n't need to consist of stuff .
One can have a lot of fun and sorrow as a material girl or boy .
But there is also the less- alloyed happiness of family , of friends , of giving help to others , of the satisfaction of work .
Pursue those things with impunity .
Happiness , while never permanent , is nonetheless real .
Life and liberty allow us to pursue happiness any way we wish .
If you want to pursue a pile of shirts , see where it gets you .
The pursuit of happiness becomes the pursuit of the definition of happiness .
And if that is what Jefferson was offering , it is as complex and challenging as a right can get .
Now that you 're free , America , what is it that you want ? That is the question one asks every morning , every night , every July 4 .
( Fireworks exploding ) I 'm Roger Rosenblatt.
Finally tonight , remembering a song and dance man who , with grace , agility , and fancy footwork soared past the racial barriers of his day to make a career on stage and in the movies .
Harold Nicholas died yesterday .
Fred Astaire said the Nicholas brothers ' leaps and splits in the 1943 movie " Stormy Weather , " made this the greatest musical number he had ever seen .
In this clip from the movie , Harold Nicholas starts out on your right .
Again , the major stories of this holiday Tuesday : Fourth of July celebrations from coast to coast , and Saudi Arabia breaks with OPEC to announce it will soon raise oil production .
Have a nice holiday evening .
We 'll see you on-line and again here tomorrow evening .
I 'm Gwen Ifill .
Thank you and good night .
```

The error occurs whether this is fed in as one line or multiple lines.

When run directly in `scala` using `processors` (`p.mkDocument(text)`), it *does* succeed in processing the document but *if* a `processor` has not yet been loaded, it takes a *long* time to make the document.  (*if* a `processor` *has* already been loaded, it's very fast, as expected)

**Comment by myedibleenso** [comment]
@michaelcapizzi, do you happen to know which line `py-processors` barfs on?

**Comment by michaelcapizzi** [comment]
@myedibleenso The line below failed to annotate.

```After I got hold of the GI Bill and we bought a house in Rockville , Maryland , at the fantastic rate of 4 1/4 percent interest , which I thought was very , very high in those days .```

**Comment by myedibleenso** [comment]
Hmm, seems to work under Python 3.  Are you using 2.x?

**Comment by myedibleenso** [comment]
I'll look into it.  `py-processors` was developed using 3.x, so there may be some encoding/decoding issues to sort out.
